import { createContext, useContext, useState } from 'react'

const T = {
  es: {
    // Navbar
    home: 'Inicio', settings: 'Configuración', logout: 'Cerrar sesión', hello: 'Hola',
    cases: 'Casos', differentials: 'Diferenciales', algorithms: 'Algoritmos',
    // Dashboard modules content
    modCasesTitle: 'Casos Clínicos',       modCasesSubtitle: 'Ramificados',
    modCasesDesc: 'Toma decisiones clínicas reales. Cada elección cambia el curso del caso y sus consecuencias.',
    modDiffTitle: 'Diagnósticos',          modDiffSubtitle: 'Diferenciales',
    modDiffDesc: 'Elimina hipótesis a medida que aparece nueva información clínica. Aprende a razonar, no a memorizar.',
    modImgTitle: 'Imágenes',               modImgSubtitle: 'Clínicas',
    modImgDesc: 'Interpreta radiografías, ECGs, TCs e histopatología con preguntas guiadas.',
    modAlgoTitle: 'Algoritmos',            modAlgoSubtitle: 'Clínicos',
    modAlgoDesc: 'Navega guías clínicas como flujos de decisión interactivos. Si X → ir a Y.',
    modAnatTitle: 'Mapa Anatómico',        modAnatSubtitle: 'Interactivo',
    modAnatDesc: 'Haz clic en un órgano o región del cuerpo para explorar sus patologías, diferenciales e imágenes.',
    modQuizTitle: 'Micro-Quizzes',         modQuizSubtitle: 'Evaluación activa',
    modQuizDesc: '¿Cuál es el siguiente paso? ¿Cuál es el error más frecuente? Feedback explicativo en cada respuesta.',
    modCommunityTitle: 'Casos Comunidad',  modCommunitySubtitle: 'Creados por estudiantes',
    modCommunityDesc: 'Casos clínicos creados y compartidos por otros estudiantes, revisados por moderadores. ¡Crea el tuyo!',
    dashboardBadge: 'Panel de aprendizaje',
    dashboardSubtitle: '¿Qué quieres practicar hoy?',
    casesCompleted: 'Casos completados',
    totalAttempts: 'Intentos totales',
    totalAvailable: 'Casos disponibles',
    modulesTitle: 'Módulos de aprendizaje',
    comingSoon: 'Próximamente',
    comingSoonSub: 'Disponible pronto',
    explore: 'Explorar →',
    pathologies: 'patologías',
    casesWord: 'casos',
    algorithmsWord: 'algoritmos',
    systems: {
      'Cardiovascular': 'Cardiovascular', 'Respiratorio': 'Respiratorio',
      'Digestivo': 'Digestivo', 'Neurológico': 'Neurológico',
      'Endocrino': 'Endocrino', 'Infeccioso': 'Infeccioso', 'Renal': 'Renal', 'Mixto': 'Mixto',
    },
    difficulties: { 'Básico': 'Básico', 'Intermedio': 'Intermedio', 'Avanzado': 'Avanzado' },
    specialties: {
      'Urgencias': 'Urgencias', 'Urgencias / UCI': 'Urgencias / UCI', 'UCI': 'UCI',
      'Urgencias / Medicina Interna': 'Urgencias / Medicina Interna',
      'Medicina Interna': 'Medicina Interna', 'Cardiología': 'Cardiología',
      'Cardiología / Urgencias': 'Cardiología / Urgencias',
      'Neurología / Urgencias': 'Neurología / Urgencias',
      'Urgencias / Endocrinología': 'Urgencias / Endocrinología',
      'Urgencias / Gastroenterología': 'Urgencias / Gastroenterología',
      'Oncología / Urgencias': 'Oncología / Urgencias',
      'Urgencias / Neumología': 'Urgencias / Neumología',
      'Urgencias / Alergología': 'Urgencias / Alergología',
    },
    // Home
    homeTitle: 'Repositorio de Patologías',
    homeSubtitle: 'Aprende medicina a través de casos clínicos interactivos',
    searchPlaceholder: 'Buscar patología...',
    filterSystem: 'Sistema', filterLevel: 'Nivel',
    allSystems: 'Todos', allLevels: 'Todas',
    pathologiesFound: 'patologías encontradas',
    pathologiesTotal: 'patologías en total',
    pathology: 'patología',
    viewCase: 'Ver caso clínico →',
    retry: 'Reintentar',
    attempt: 'intento', attempts: 'intentos',
    noResults: 'No se encontraron patologías.',
    completed: '✓ Completado', withErrors: '! Con errores', failed: '✕ Fallido',
    // Pathology
    backToRepo: '← Volver al repositorio',
    clinicalCase: 'Caso Clínico',
    decision: 'Decisión',
    continueBtn: 'Continuar →',
    correctLabel: 'Correcto.', incorrectLabel: 'Incorrecto.',
    repeatCase: 'Repetir caso',
    viewOtherPathologies: 'Ver otras patologías',
    goHome: 'Ir al inicio',
    yourPath: 'Tu recorrido',
    progressSaved: '✓ Progreso guardado en tu cuenta',
    loading: 'Cargando...',
    errorLoading: 'Error al cargar el caso',
    // Pathology terminal
    caseSuccess: 'Caso completado con éxito',
    caseWarning: 'Caso completado con observaciones',
    caseFailure: 'Desenlace adverso',
    clinicalPearl: 'Perla clínica',
    // Differentials
    interactiveMode: 'Modo interactivo',
    differentialsTitle: 'Diagnósticos Diferenciales',
    differentialsSubtitle: 'Se te presenta un caso clínico y debes ir eliminando hipótesis a medida que aparece nueva información.',
    searchDiff: 'Buscar caso...',
    allDiff: 'Todos',
    startDiagnosis: 'Iniciar diagnóstico →',
    hypotheses: 'hipótesis',
    casesFound: 'casos encontrados',
    casesTotal: 'casos en total',
    case: 'caso',
    noResultsDiff: 'No se encontraron casos.',
    // DifferentialCase
    backToDiff: '← Volver a diagnósticos diferenciales',
    clinicalPresentation: 'Presentación clínica',
    yourRoute: 'Recorrido',
    goBack: '← Retroceder un paso',
    noDecisions: 'Las decisiones que tomes aparecerán aquí.',
    newInfo: 'Nueva información — Pista',
    selectHypotheses: 'Selecciona las hipótesis que puedes eliminar con la información actual',
    eliminate: 'Eliminar',
    hypothesisSelected: 'hipótesis seleccionada',
    hypothesesSelected: 'hipótesis seleccionadas',
    selectToEliminate: 'Selecciona diagnósticos a eliminar',
    result: 'Resultado',
    correctElim: 'eliminación correcta',
    correctElims: 'eliminaciones correctas',
    shouldNotElim: 'no debía eliminarse aún',
    shouldNotElims: 'no debían eliminarse aún',
    didNotElim: 'Dejaste sin eliminar',
    diagnosis: 'diagnóstico', diagnoses: 'diagnósticos',
    nextClue: 'Siguiente pista →',
    seeResolution: 'Ver resolución →',
    diagnosisConfirmed: 'Diagnóstico confirmado',
    repeatDiff: 'Repetir',
    otherCases: 'Otros casos',
    // Algorithms
    guidesMode: 'Guías interactivas',
    algorithmsTitle: 'Algoritmos Clínicos',
    algorithmsSubtitle: 'Navega guías clínicas como flujos de decisión. Si el paciente presenta X → ir a Y.',
    searchAlgo: 'Buscar algoritmo...',
    allSpecialties: 'Todas',
    specialty: 'Especialidad',
    startAlgorithm: 'Iniciar algoritmo →',
    nodes: 'nodos',
    basedOn: 'Basado en:',
    algorithmsFound: 'algoritmos encontrados',
    algorithmsTotal: 'algoritmos disponibles',
    algorithm: 'algoritmo',
    noResultsAlgo: 'No se encontraron algoritmos.',
    // AlgorithmCase
    backToAlgo: '← Volver a algoritmos',
    decisionLabel: 'Decisión',
    actions: 'Acciones',
    restartAlgo: 'Reiniciar algoritmo',
    otherAlgorithms: 'Otros algoritmos',
    severityCritical: 'Crítico', severityWarning: 'Precaución',
    severityInfo: 'Informativo', severitySuccess: 'Favorable',
    // Settings
    settingsTitle: 'Configuración',
    profile: 'Mi perfil',
    name: 'Nombre completo', email: 'Correo electrónico',
    saveChanges: 'Guardar cambios', saving: 'Guardando...', saved: 'Cambios guardados',
    changePassword: 'Cambiar contraseña',
    currentPassword: 'Contraseña actual', newPassword: 'Nueva contraseña',
    updatePassword: 'Actualizar contraseña', passwordUpdated: 'Contraseña actualizada',
    language: 'Idioma', chooseLanguage: 'Selecciona el idioma de la interfaz',
    stats: 'Mis estadísticas',
    casesStat: 'Completados', casesWarning: 'Con errores', casesFailed: 'Fallidos',
    notPlayed: 'Aún no has jugado ningún caso.',
    // Login
    loginSubtitle: 'Inicia sesión para continuar',
    emailLabel: 'Correo electrónico',
    passwordLabel: 'Contraseña',
    loginBtn: 'Iniciar sesión', loggingIn: 'Ingresando...',
    noAccount: '¿No tienes cuenta?', register: 'Regístrate',
    // Register
    registerSubtitle: 'Crea tu cuenta gratuita',
    nameLabel: 'Nombre completo',
    passwordHint: 'Mínimo 6 caracteres',
    registerBtn: 'Crear cuenta', registering: 'Creando cuenta...',
    hasAccount: '¿Ya tienes cuenta?', loginLink: 'Inicia sesión',
  },
  en: {
    // Navbar
    home: 'Home', settings: 'Settings', logout: 'Log out', hello: 'Hello',
    cases: 'Cases', differentials: 'Differentials', algorithms: 'Algorithms',
    // Dashboard modules content
    modCasesTitle: 'Clinical Cases',       modCasesSubtitle: 'Branching',
    modCasesDesc: 'Make real clinical decisions. Each choice changes the course of the case and its consequences.',
    modDiffTitle: 'Diagnoses',             modDiffSubtitle: 'Differential',
    modDiffDesc: 'Eliminate hypotheses as new clinical information appears. Learn to reason, not to memorize.',
    modImgTitle: 'Images',                 modImgSubtitle: 'Clinical',
    modImgDesc: 'Interpret X-rays, ECGs, CTs and histopathology with guided questions.',
    modAlgoTitle: 'Algorithms',            modAlgoSubtitle: 'Clinical',
    modAnatTitle: 'Anatomical Map',        modAnatSubtitle: 'Interactive',
    modAnatDesc: 'Click on an organ or body region to explore its pathologies, differentials and images.',
    modQuizTitle: 'Micro-Quizzes',         modQuizSubtitle: 'Active assessment',
    modQuizDesc: "What's the next step? What's the most common error? Explanatory feedback on every answer.",
    modCommunityTitle: 'Community Cases',  modCommunitySubtitle: 'Created by students',
    modCommunityDesc: 'Clinical cases created and shared by fellow students, reviewed by moderators. Create your own!',
    modAlgoDesc: 'Navigate clinical guidelines as interactive decision flowcharts. If X → go to Y.',
    dashboardBadge: 'Learning dashboard',
    dashboardSubtitle: 'What do you want to practice today?',
    casesCompleted: 'Cases completed',
    totalAttempts: 'Total attempts',
    totalAvailable: 'Cases available',
    modulesTitle: 'Learning modules',
    comingSoon: 'Coming soon',
    comingSoonSub: 'Available soon',
    explore: 'Explore →',
    pathologies: 'pathologies',
    casesWord: 'cases',
    algorithmsWord: 'algorithms',
    systems: {
      'Cardiovascular': 'Cardiovascular', 'Respiratorio': 'Respiratory',
      'Digestivo': 'Digestive', 'Neurológico': 'Neurological',
      'Endocrino': 'Endocrine', 'Infeccioso': 'Infectious', 'Renal': 'Renal', 'Mixto': 'Mixed',
    },
    difficulties: { 'Básico': 'Basic', 'Intermedio': 'Intermediate', 'Avanzado': 'Advanced' },
    specialties: {
      'Urgencias': 'Emergency', 'Urgencias / UCI': 'Emergency / ICU', 'UCI': 'ICU',
      'Urgencias / Medicina Interna': 'Emergency / Internal Medicine',
      'Medicina Interna': 'Internal Medicine', 'Cardiología': 'Cardiology',
      'Cardiología / Urgencias': 'Cardiology / Emergency',
      'Neurología / Urgencias': 'Neurology / Emergency',
      'Urgencias / Endocrinología': 'Emergency / Endocrinology',
      'Urgencias / Gastroenterología': 'Emergency / Gastroenterology',
      'Oncología / Urgencias': 'Oncology / Emergency',
      'Urgencias / Neumología': 'Emergency / Pulmonology',
      'Urgencias / Alergología': 'Emergency / Allergology',
    },
    // Home
    homeTitle: 'Pathology Repository',
    homeSubtitle: 'Learn medicine through interactive clinical cases',
    searchPlaceholder: 'Search pathology...',
    filterSystem: 'System', filterLevel: 'Level',
    allSystems: 'All', allLevels: 'All',
    pathologiesFound: 'pathologies found',
    pathologiesTotal: 'pathologies total',
    pathology: 'pathology',
    viewCase: 'View clinical case →',
    retry: 'Retry',
    attempt: 'attempt', attempts: 'attempts',
    noResults: 'No pathologies found.',
    completed: '✓ Completed', withErrors: '! With errors', failed: '✕ Failed',
    // Pathology
    backToRepo: '← Back to repository',
    clinicalCase: 'Clinical Case',
    decision: 'Decision',
    continueBtn: 'Continue →',
    correctLabel: 'Correct.', incorrectLabel: 'Incorrect.',
    repeatCase: 'Repeat case',
    viewOtherPathologies: 'View other pathologies',
    goHome: 'Go to home',
    yourPath: 'Your path',
    progressSaved: '✓ Progress saved to your account',
    loading: 'Loading...',
    errorLoading: 'Error loading case',
    // Pathology terminal
    caseSuccess: 'Case completed successfully',
    caseWarning: 'Case completed with observations',
    caseFailure: 'Adverse outcome',
    clinicalPearl: 'Clinical pearl',
    // Differentials
    interactiveMode: 'Interactive mode',
    differentialsTitle: 'Differential Diagnoses',
    differentialsSubtitle: 'A clinical case is presented and you must eliminate hypotheses as new information appears.',
    searchDiff: 'Search case...',
    allDiff: 'All',
    startDiagnosis: 'Start diagnosis →',
    hypotheses: 'hypotheses',
    casesFound: 'cases found',
    casesTotal: 'cases total',
    case: 'case',
    noResultsDiff: 'No cases found.',
    // DifferentialCase
    backToDiff: '← Back to differential diagnoses',
    clinicalPresentation: 'Clinical presentation',
    yourRoute: 'Route',
    goBack: '← Go back one step',
    noDecisions: 'The decisions you make will appear here.',
    newInfo: 'New information — Clue',
    selectHypotheses: 'Select the hypotheses you can eliminate with the current information',
    eliminate: 'Eliminate',
    hypothesisSelected: 'hypothesis selected',
    hypothesesSelected: 'hypotheses selected',
    selectToEliminate: 'Select diagnoses to eliminate',
    result: 'Result',
    correctElim: 'correct elimination',
    correctElims: 'correct eliminations',
    shouldNotElim: 'should not be eliminated yet',
    shouldNotElims: 'should not be eliminated yet',
    didNotElim: 'You did not eliminate',
    diagnosis: 'diagnosis', diagnoses: 'diagnoses',
    nextClue: 'Next clue →',
    seeResolution: 'See resolution →',
    diagnosisConfirmed: 'Diagnosis confirmed',
    repeatDiff: 'Repeat',
    otherCases: 'Other cases',
    // Algorithms
    guidesMode: 'Interactive guides',
    algorithmsTitle: 'Clinical Algorithms',
    algorithmsSubtitle: 'Navigate clinical guidelines as decision flowcharts. If patient has X → go to Y.',
    searchAlgo: 'Search algorithm...',
    allSpecialties: 'All',
    specialty: 'Specialty',
    startAlgorithm: 'Start algorithm →',
    nodes: 'nodes',
    basedOn: 'Based on:',
    algorithmsFound: 'algorithms found',
    algorithmsTotal: 'algorithms available',
    algorithm: 'algorithm',
    noResultsAlgo: 'No algorithms found.',
    // AlgorithmCase
    backToAlgo: '← Back to algorithms',
    decisionLabel: 'Decision',
    actions: 'Actions',
    restartAlgo: 'Restart algorithm',
    otherAlgorithms: 'Other algorithms',
    severityCritical: 'Critical', severityWarning: 'Caution',
    severityInfo: 'Informational', severitySuccess: 'Favorable',
    // Settings
    settingsTitle: 'Settings',
    profile: 'My profile',
    name: 'Full name', email: 'Email address',
    saveChanges: 'Save changes', saving: 'Saving...', saved: 'Changes saved',
    changePassword: 'Change password',
    currentPassword: 'Current password', newPassword: 'New password',
    updatePassword: 'Update password', passwordUpdated: 'Password updated',
    language: 'Language', chooseLanguage: 'Select the interface language',
    stats: 'My statistics',
    casesStat: 'Completed', casesWarning: 'With errors', casesFailed: 'Failed',
    notPlayed: "You haven't played any case yet.",
    // Login
    loginSubtitle: 'Sign in to continue',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    loginBtn: 'Sign in', loggingIn: 'Signing in...',
    noAccount: "Don't have an account?", register: 'Sign up',
    // Register
    registerSubtitle: 'Create your free account',
    nameLabel: 'Full name',
    passwordHint: 'At least 6 characters',
    registerBtn: 'Create account', registering: 'Creating account...',
    hasAccount: 'Already have an account?', loginLink: 'Sign in',
  },
}

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('medex_lang') || 'es')

  const changeLang = (l) => {
    localStorage.setItem('medex_lang', l)
    setLang(l)
  }

  return (
    <LangContext.Provider value={{ lang, changeLang, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
